# Generated by Django 5.1 on 2024-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom1', models.CharField(max_length=100)),
                ('nom2', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('button', models.CharField(max_length=50)),
            ],
        ),
    ]
