# Generated by Django 5.1 on 2024-09-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='img',
        ),
    ]
