# Generated by Django 5.1 on 2024-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_card_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cap',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
