# Generated by Django 5.1 on 2024-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_card_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100)),
                ('nomi', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('nom1', models.CharField(max_length=100)),
                ('nom2', models.CharField(max_length=100)),
                ('nom3', models.CharField(max_length=100)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
            ],
        ),
    ]
