# Generated by Django 5.1 on 2024-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_legal_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ism', models.CharField(max_length=150)),
                ('lavozim', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
