# Generated by Django 5.1 on 2024-09-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_contact_qosh_email_remove_contact_qosh_ism_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_qosh',
        ),
    ]
