# Generated by Django 5.1 on 2024-09-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_qosh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_qosh',
            new_name='Qosh',
        ),
    ]
