# Generated by Django 5.1 on 2024-09-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_contact_qosh_qosh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qosh',
            new_name='SMs',
        ),
    ]
