# Generated by Django 5.0.3 on 2024-09-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_qosh_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='nomi1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi1_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='yozuv_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='yozuv_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='yozuv_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
