# Generated by Django 5.0.3 on 2024-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_home_nomi1_en_home_nomi1_ru_home_nomi1_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cap_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cap_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cap_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='ism_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='ism_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='ism_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='lavozim_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='lavozim_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='lavozim_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom1_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nomi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nomi_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text1_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text2_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text3_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text3_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text3_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='to_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='to_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='to_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='button_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='button_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='button_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom1_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom2_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom2_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom2_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
