# Generated by Django 5.0.3 on 2024-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_card_cap_en_card_cap_ru_card_cap_uz_card_nomi_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rasm',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
