# Generated by Django 5.0.3 on 2024-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_cap_ru_card_cap_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cap_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='ism_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='lavozim_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card1',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='yozuv_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nomi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text3_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='to_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='button_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom2_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
