# Generated by Django 5.0.3 on 2024-10-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_card_cap_ru_card_nomi_ru_card_text_ru_card1_ism_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cap_ru',
        ),
        migrations.RemoveField(
            model_name='card',
            name='nomi_ru',
        ),
        migrations.RemoveField(
            model_name='card',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='card1',
            name='ism_ru',
        ),
        migrations.RemoveField(
            model_name='card1',
            name='lavozim_ru',
        ),
        migrations.RemoveField(
            model_name='card1',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='home',
            name='nomi1_ru',
        ),
        migrations.RemoveField(
            model_name='home',
            name='nomi2_ru',
        ),
        migrations.RemoveField(
            model_name='home',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='home',
            name='yozuv_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='nom1_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='nom2_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='nom3_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='nomi_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='text1_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='text2_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='text3_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='to_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='button_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='nom1_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='nom2_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text_ru',
        ),
    ]
