# Generated by Django 5.0.3 on 2024-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_card_cap_ru_remove_card_nomi_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
