# Generated by Django 5.0.3 on 2024-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_hed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnomi1', models.CharField(max_length=300)),
                ('rnomi2', models.CharField(max_length=400)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi1', models.CharField(max_length=500)),
                ('nomi2', models.CharField(max_length=600)),
            ],
        ),
    ]
