# Generated by Django 5.0.3 on 2024-10-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_anq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('arch', models.CharField(max_length=200)),
                ('raqam1', models.IntegerField()),
                ('awards', models.CharField(max_length=200)),
                ('raqam2', models.IntegerField()),
                ('reseller', models.CharField(max_length=200)),
                ('raqam3', models.IntegerField()),
                ('uncateg', models.CharField(max_length=200)),
                ('raqam4', models.IntegerField()),
                ('interv', models.CharField(max_length=200)),
                ('raqam5', models.IntegerField()),
                ('event', models.CharField(max_length=200)),
                ('raqam6', models.IntegerField()),
            ],
        ),
    ]
