# Generated by Django 5.0.3 on 2024-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_categ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('sana', models.CharField(max_length=200)),
            ],
        ),
    ]
