# Generated by Django 5.0.3 on 2024-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_oy'),
    ]

    operations = [
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
