# Generated by Django 5.0.3 on 2024-10-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rasm1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rasm1',
        ),
    ]
