# Generated by Django 5.1.2 on 2024-10-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_delete_rasm1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='yozuv',
        ),
        migrations.RemoveField(
            model_name='home',
            name='yozuv_en',
        ),
        migrations.RemoveField(
            model_name='home',
            name='yozuv_ja',
        ),
    ]
