# Generated by Django 5.1.2 on 2024-10-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_home_yozuv_remove_home_yozuv_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recent',
        ),
    ]
