# Generated by Django 5.1.2 on 2024-10-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_delete_recent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anq',
        ),
    ]
