# Generated by Django 5.1.2 on 2024-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_delete_anq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='text',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='text_ja',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='to',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='to_en',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='to_ja',
        ),
        migrations.AddField(
            model_name='legal',
            name='emad',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legal',
            name='emad_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='emad_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='estate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legal',
            name='estate_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='estate_ja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
