# Generated by Django 5.1.2 on 2024-10-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_legal_text_remove_legal_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='emad',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='emad_en',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='emad_ja',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='estate',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='estate_en',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='estate_ja',
        ),
        migrations.AddField(
            model_name='card',
            name='emad',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='emad_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='emad_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='estate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='estate_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='estate_ja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
