# Generated by Django 5.1.2 on 2024-10-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_legal_emad_remove_legal_emad_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='card',
            name='nomi_en',
        ),
        migrations.RemoveField(
            model_name='card',
            name='nomi_ja',
        ),
    ]
