# Generated by Django 5.1.2 on 2024-10-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_card_nomi_remove_card_nomi_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card1',
        ),
    ]
