# Generated by Django 5.1.2 on 2024-10-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_oy_nomi_alter_oy_raqam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oy',
            name='raqam',
        ),
        migrations.AlterField(
            model_name='oy',
            name='nomi',
            field=models.CharField(max_length=200, verbose_name='newsdagi buttondi nomini krting: '),
        ),
    ]
