# Generated by Django 5.1.2 on 2024-10-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_oy_raqam_alter_oy_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsdagi_malumot_ongtomondagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('nomi_en', models.CharField(max_length=200, null=True)),
                ('nomi_ja', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ja', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='P',
        ),
    ]
