# Generated by Django 5.1.2 on 2024-10-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_newsdagi_malumot_ongtomondagi_delete_p'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rasm',
        ),
    ]
