# Generated by Django 5.1.2 on 2024-10-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_delete_rasm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OY',
            new_name='Newsdi_button',
        ),
    ]
