# Generated by Django 5.1.2 on 2024-10-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_rename_oy_newsdi_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsdagi_Categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ja', models.CharField(max_length=200, null=True)),
                ('nomi1', models.CharField(max_length=200)),
                ('nomi1_en', models.CharField(max_length=200, null=True)),
                ('nomi1_ja', models.CharField(max_length=200, null=True)),
                ('raqam1', models.IntegerField()),
                ('raqam1_en', models.IntegerField(null=True)),
                ('raqam1_ja', models.IntegerField(null=True)),
                ('nomi2', models.CharField(max_length=200)),
                ('nomi2_en', models.CharField(max_length=200, null=True)),
                ('nomi2_ja', models.CharField(max_length=200, null=True)),
                ('raqam2', models.IntegerField()),
                ('raqam2_en', models.IntegerField(null=True)),
                ('raqam2_ja', models.IntegerField(null=True)),
                ('nomi3', models.CharField(max_length=200)),
                ('nomi3_en', models.CharField(max_length=200, null=True)),
                ('nomi3_ja', models.CharField(max_length=200, null=True)),
                ('raqam3', models.IntegerField()),
                ('raqam3_en', models.IntegerField(null=True)),
                ('raqam3_ja', models.IntegerField(null=True)),
                ('nomi4', models.CharField(max_length=200)),
                ('nomi4_en', models.CharField(max_length=200, null=True)),
                ('nomi4_ja', models.CharField(max_length=200, null=True)),
                ('raqam4', models.IntegerField()),
                ('raqam4_en', models.IntegerField(null=True)),
                ('raqam4_ja', models.IntegerField(null=True)),
                ('nomi5', models.CharField(max_length=200)),
                ('nomi5_en', models.CharField(max_length=200, null=True)),
                ('nomi5_ja', models.CharField(max_length=200, null=True)),
                ('raqam5', models.IntegerField()),
                ('raqam5_en', models.IntegerField(null=True)),
                ('raqam5_ja', models.IntegerField(null=True)),
                ('nomi6', models.CharField(max_length=200)),
                ('nomi6_en', models.CharField(max_length=200, null=True)),
                ('nomi6_ja', models.CharField(max_length=200, null=True)),
                ('raqam6', models.IntegerField()),
                ('raqam6_en', models.IntegerField(null=True)),
                ('raqam6_ja', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Categ',
        ),
    ]
