# Generated by Django 5.1.2 on 2024-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_newsdagi_rasm_delete_ra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsdagi_rasmdi_tagdagi_sozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_ja', models.CharField(max_length=300, null=True)),
                ('title_small', models.CharField(max_length=400)),
                ('title_small_en', models.CharField(max_length=400, null=True)),
                ('title_small_ja', models.CharField(max_length=400, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ja', models.TextField(null=True)),
                ('button_nomi', models.CharField(max_length=400)),
                ('button_nomi_en', models.CharField(max_length=400, null=True)),
                ('button_nomi_ja', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Short',
        ),
    ]
