# Generated by Django 5.1.2 on 2024-10-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_newsdagi_rasmdi_tagdagi_sozlar_delete_short'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hed',
            new_name='Projecti_Home',
        ),
    ]
