# Generated by Django 5.1.2 on 2024-10-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_hed_projecti_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kard',
            new_name='Project_Kard',
        ),
    ]
