# Generated by Django 5.1.2 on 2024-10-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_rasm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rasm',
        ),
    ]
