# Generated by Django 5.1.2 on 2024-10-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_delete_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boshqsmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
