# Generated by Django 5.1.2 on 2024-10-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_boshqsmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdagi_categ',
            name='nomi6',
        ),
        migrations.RemoveField(
            model_name='newsdagi_categ',
            name='nomi6_en',
        ),
        migrations.RemoveField(
            model_name='newsdagi_categ',
            name='nomi6_ja',
        ),
        migrations.RemoveField(
            model_name='newsdagi_categ',
            name='raqam6',
        ),
        migrations.RemoveField(
            model_name='newsdagi_categ',
            name='raqam6_en',
        ),
        migrations.RemoveField(
            model_name='newsdagi_categ',
            name='raqam6_ja',
        ),
    ]
