# Generated by Django 5.1.2 on 2024-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_newsdagi_categ_nomi6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam1_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam2_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam3_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam4_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam5',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam5_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsdagi_categ',
            name='raqam5_ja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
