# Generated by Django 5.1.2 on 2024-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_newsdagi_categ_raqam1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsdi_button',
            old_name='nomi',
            new_name='nomi1',
        ),
        migrations.AddField(
            model_name='newsdi_button',
            name='nomi2',
            field=models.CharField(default=1, max_length=200, verbose_name='newsdagi buttondi nomini krting: '),
            preserve_default=False,
        ),
    ]
