# Generated by Django 5.1.2 on 2024-10-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_rename_nomi_newsdi_button_nomi1_newsdi_button_nomi2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdi_button',
            name='nomi1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsdi_button',
            name='nomi2',
            field=models.CharField(max_length=200),
        ),
    ]
