# Generated by Django 5.1.2 on 2024-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_newsdagideta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('title4', models.CharField(max_length=200)),
            ],
        ),
    ]
