# Generated by Django 5.1.2 on 2024-10-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='title1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title1_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title2_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title3_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title4_ja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
