# Generated by Django 5.1.2 on 2024-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_header_title1_en_header_title1_ja_header_title2_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title1_en', models.CharField(max_length=200, null=True)),
                ('title1_ja', models.CharField(max_length=200, null=True)),
                ('title2', models.CharField(max_length=200)),
                ('title2_en', models.CharField(max_length=200, null=True)),
                ('title2_ja', models.CharField(max_length=200, null=True)),
                ('title3', models.CharField(max_length=200)),
                ('title3_en', models.CharField(max_length=200, null=True)),
                ('title3_ja', models.CharField(max_length=200, null=True)),
                ('title4', models.CharField(max_length=200)),
                ('title4_en', models.CharField(max_length=200, null=True)),
                ('title4_ja', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
