# Generated by Django 5.1.2 on 2024-10-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_header_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_kard',
            name='nomi1_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='nomi1_ja',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='nomi2_en',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='nomi2_ja',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='rnomi1_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='rnomi1_ja',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='rnomi2_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='rnomi2_ja',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
