# Generated by Django 5.1.2 on 2024-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_project_kard_nomi1_en_project_kard_nomi1_ja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Matn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ja', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ja', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Matn1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ja', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ja', models.TextField(null=True)),
            ],
        ),
    ]
