# Generated by Django 5.1.2 on 2024-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_header_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=300)),
                ('title1_en', models.CharField(max_length=300, null=True)),
                ('title1_ja', models.CharField(max_length=300, null=True)),
                ('text1', models.TextField()),
                ('text1_en', models.TextField(null=True)),
                ('text1_ja', models.TextField(null=True)),
                ('title2', models.CharField(max_length=300)),
                ('title2_en', models.CharField(max_length=300, null=True)),
                ('title2_ja', models.CharField(max_length=300, null=True)),
                ('text2', models.TextField()),
                ('text2_en', models.TextField(null=True)),
                ('text2_ja', models.TextField(null=True)),
                ('title3', models.CharField(max_length=300)),
                ('title3_en', models.CharField(max_length=300, null=True)),
                ('title3_ja', models.CharField(max_length=300, null=True)),
                ('text3', models.TextField()),
                ('text3_en', models.TextField(null=True)),
                ('text3_ja', models.TextField(null=True)),
            ],
        ),
    ]
