# Generated by Django 5.1.2 on 2024-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_news_butondi_tepasdagi_matn'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdagideta',
            name='button_nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='button_nomi_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi1_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi2_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi3_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='ong1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='ong1_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='ong2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='ong2_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='titlesmal_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='titlesmal_ja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
