# Generated by Django 5.1.2 on 2024-10-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_remove_card_cap_en_remove_card_emad_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cap_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='emad_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='estate_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header_news',
            name='title1_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='header_news',
            name='title2_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='header_news',
            name='title3_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='header_news',
            name='title4_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='header_project',
            name='title1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header_project',
            name='title2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header_project',
            name='title3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header_project',
            name='title4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nom3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='text3_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news_butondi_tepasdagi_matn',
            name='title1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news_butondi_tepasdagi_matn',
            name='title2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news_butondi_tepasdagi_matn',
            name='title3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='nomi1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='nomi2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='nomi3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='nomi4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='nomi5_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='raqam1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='raqam2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='raqam3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='raqam4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='raqam5_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_categ',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_malumot_ongtomondagi',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_malumot_ongtomondagi',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_rasmdi_tagdagi_sozlar',
            name='button_nomi_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_rasmdi_tagdagi_sozlar',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_rasmdi_tagdagi_sozlar',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newsdagi_rasmdi_tagdagi_sozlar',
            name='title_small_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='button_nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='ong1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='ong2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsdagideta',
            name='titlesmal_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='nomi1_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='nomi2_en',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='rnomi1_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project_kard',
            name='rnomi2_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project_matn',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project_matn',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_matn1',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project_matn1',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='button_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nom2_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='words_news',
            name='text1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='words_news',
            name='text2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='words_news',
            name='text3_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='words_news',
            name='title1_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='words_news',
            name='title2_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='words_news',
            name='title3_en',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
