# Generated by Django 5.1.2 on 2024-10-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_card_cap_en_card_emad_en_card_estate_en_card_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News2_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrqagaRasm', models.ImageField(upload_to='media/')),
                ('ikonkarasm', models.ImageField(upload_to='media/')),
                ('ikonkanomi', models.CharField(max_length=300)),
                ('nomi2', models.CharField(max_length=300)),
                ('nomi2_davomi', models.CharField(max_length=300)),
                ('matn', models.CharField(max_length=400)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('ism', models.CharField(max_length=300)),
                ('manzil', models.CharField(max_length=300)),
                ('ikonkarasm2', models.ImageField(upload_to='media/')),
                ('ikonkanomi2', models.CharField(max_length=300)),
                ('nomi3', models.CharField(max_length=200)),
                ('nomer', models.IntegerField()),
                ('nomi4', models.CharField(max_length=300)),
                ('emailnom', models.CharField(max_length=300)),
                ('nom5', models.CharField(max_length=300)),
                ('nom6', models.CharField(max_length=300)),
                ('whatsappimg', models.ImageField(upload_to='media/')),
                ('whatsappnomi', models.CharField(max_length=300)),
                ('emailimg', models.ImageField(upload_to='media/')),
                ('nomiemail', models.CharField(max_length=300)),
                ('callimg', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
