# Generated by Django 5.1.2 on 2024-10-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_news2_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News2_Home',
        ),
    ]
