# Generated by Django 5.1.2 on 2024-10-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_alter_pdfhome2_nomi1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfBurj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('nomi1', models.CharField(max_length=300)),
                ('nomi2', models.CharField(max_length=300)),
                ('nomi3', models.CharField(max_length=300)),
                ('nomi4', models.CharField(max_length=300)),
                ('nomi5', models.CharField(max_length=300)),
            ],
        ),
    ]
