# Generated by Django 5.1.2 on 2024-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_pdfburj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfburj',
            name='nomi6',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
