# Generated by Django 5.1.2 on 2024-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_pdftxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
