# Generated by Django 5.1.2 on 2024-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_pdfimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfimg',
            name='img2',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfimg',
            name='img3',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfimg',
            name='img4',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfimg',
            name='img5',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
