# Generated by Django 5.1.2 on 2024-10-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_pdfimg_img2_pdfimg_img3_pdfimg_img4_pdfimg_img5'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfimg',
            name='img6',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfimg',
            name='img7',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfimg',
            name='img8',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfimg',
            name='img9',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
