# Generated by Django 5.1.2 on 2024-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_project_kard_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf10Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi1', models.CharField(max_length=200)),
                ('nomi2', models.CharField(max_length=299)),
                ('nomi3', models.CharField(max_length=299)),
                ('baytxt', models.CharField(max_length=300)),
                ('baground_Rasm', models.ImageField(upload_to='media/')),
                ('rasm1', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
