# Generated by Django 5.1.2 on 2024-11-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_pdf10home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pdf10Home',
            new_name='Pdf8Home',
        ),
    ]
