# Generated by Django 5.1.2 on 2024-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_pdfburj8'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTxt8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('nomi1', models.CharField(max_length=300)),
                ('text3', models.TextField()),
                ('nomi2', models.CharField(max_length=300)),
                ('nomi3', models.CharField(max_length=300)),
                ('nomi4', models.CharField(max_length=300)),
                ('nomi5', models.CharField(max_length=300)),
                ('nomi6', models.CharField(max_length=300)),
                ('text4', models.TextField()),
                ('text5', models.TextField()),
                ('text6', models.TextField()),
            ],
        ),
    ]
