# Generated by Django 5.1.2 on 2024-11-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_pdftxt8'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftxt8',
            name='text7',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftxt8',
            name='text8',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftxt8',
            name='text9',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
