# Generated by Django 5.1.2 on 2024-11-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_pdfimg8'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfimg8',
            old_name='img',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='pdfimg8',
            name='img10',
        ),
        migrations.RemoveField(
            model_name='pdfimg8',
            name='img9',
        ),
    ]
