# Generated by Django 5.1.2 on 2024-11-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_pdfburj3_pdftxt3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfburj3',
            name='nomi6',
        ),
    ]
