# Generated by Django 5.1.2 on 2024-11-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_remove_pdfburj3_nomi6'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfburj3',
            name='nomi6',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfburj3',
            name='nomi7',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfburj3',
            name='nomi8',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfburj3',
            name='nomi9',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
