# Generated by Django 5.1.2 on 2024-11-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_pdfburj3_nomi6_pdfburj3_nomi7_pdfburj3_nomi8_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasm3Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
