# Generated by Django 5.1.2 on 2024-11-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_rasm44pdf_rasm4pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rasm44Pdf',
            new_name='Img44Pdf',
        ),
    ]
