# Generated by Django 5.1.2 on 2024-11-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_pdf5home_pdfhome5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdfHome5',
            new_name='PdfHome5E',
        ),
    ]
