# Generated by Django 5.1.2 on 2024-11-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_rename_pdfhome5_pdfhome5e'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdfHome5E',
            new_name='Pdfooo545',
        ),
    ]
