# Generated by Django 5.1.2 on 2024-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_pdfburj5_pdftxt5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img55Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='PdfImg05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media/')),
                ('img2', models.ImageField(upload_to='media/')),
                ('img3', models.ImageField(upload_to='media/')),
                ('img4', models.ImageField(upload_to='media/')),
                ('img5', models.ImageField(upload_to='media/')),
                ('img6', models.ImageField(upload_to='media/')),
                ('img7', models.ImageField(upload_to='media/')),
                ('img8', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Rasm5Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
