# Generated by Django 5.1.2 on 2024-11-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_img55pdf_pdfimg05_rasm5pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img55Pdf',
        ),
    ]
