# Generated by Django 5.1.2 on 2024-11-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_delete_img55pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rasm5Pdf',
        ),
    ]
