# Generated by Django 5.1.2 on 2024-11-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_rasm5pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfCard005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi1', models.CharField(max_length=300)),
                ('nomi2', models.CharField(max_length=300)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PdfCard05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='PdfPast005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm1', models.ImageField(upload_to='media/')),
                ('rasm2', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
