# Generated by Django 5.1.2 on 2024-11-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_pdf9_pdf9home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pdf9Home',
            new_name='PDF9HOMES',
        ),
        migrations.RenameModel(
            old_name='Pdf9',
            new_name='PDF9HOMES2',
        ),
    ]
