# Generated by Django 5.1.2 on 2024-11-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_pdfburj9_pdftxt9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfburj9',
            name='nomi6',
        ),
        migrations.RemoveField(
            model_name='pdfburj9',
            name='nomi7',
        ),
        migrations.RemoveField(
            model_name='pdfburj9',
            name='nomi8',
        ),
        migrations.RemoveField(
            model_name='pdfburj9',
            name='nomi9',
        ),
    ]
