# Generated by Django 5.1.2 on 2024-11-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_remove_pdfburj9_nomi6_remove_pdfburj9_nomi7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfburj9',
            name='nomi6',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
