# Generated by Django 5.1.2 on 2024-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_pdfburj9_nomi6'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfburj9',
            name='nomi7',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
