# Generated by Django 5.1.2 on 2024-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_pdfburj9_nomi7'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftxt9',
            name='text10',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftxt9',
            name='text7',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftxt9',
            name='text8',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftxt9',
            name='text9',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
