# Generated by Django 5.1.2 on 2024-11-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_pdftxt9_text10_pdftxt9_text7_pdftxt9_text8_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfImg09',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media/')),
                ('img2', models.ImageField(upload_to='media/')),
                ('img3', models.ImageField(upload_to='media/')),
                ('img4', models.ImageField(upload_to='media/')),
                ('img5', models.ImageField(upload_to='media/')),
                ('img6', models.ImageField(upload_to='media/')),
                ('img7', models.ImageField(upload_to='media/')),
                ('img8', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
