# Generated by Django 5.1.2 on 2024-11-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_rasm9pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rasm9Pdf',
        ),
    ]
