# Generated by Django 5.1.2 on 2024-11-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_delete_rasm9pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfCard009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
